import logging
from typing import Dict, List, Tuple

import requests

from cache import cached
from config import CURRENCYLAYER_API_KEY
from exceptions import ExchangeRateError

logger = logging.getLogger(__name__)

BASE_URL = "https://api.currencylayer.com/live"
REQUEST_TIMEOUT = 15

currency_names_ru: Dict[str, str] = {
      "AED": "Дирхам ОАЭ",
    "AFN": "Афгани",
    "ALL": "Албанский лек",
    "AMD": "Армянский драм",
    "ANG": "Нидерландский антильский гульден",
    "AOA": "Ангольская кванза",
    "ARS": "Аргентинское песо",
    "AUD": "Австралийский доллар",
    "AWG": "Арубанский флорин",
    "AZN": "Азербайджанский манат",
    "BAM": "Боснийская конвертируемая марка",
    "BBD": "Барбадосский доллар",
    "BDT": "Бангладешская така",
    "BGN": "Болгарский лев",
    "BHD": "Бахрейнский динар",
    "BIF": "Бурундийский франк",
    "BMD": "Бермудский доллар",
    "BND": "Брунейский доллар",
    "BOB": "Боливийский боливиано",
    "BRL": "Бразильский реал",
    "BSD": "Багамский доллар",
    "BTC": "Биткойн",
    "BTN": "Бутанский нгултрум",
    "BWP": "Ботсванская пула",
    "BYN": "Белорусский рубль",
    "BYR": "Белорусский рубль (старый)",
    "BZD": "Белизский доллар",
    "CAD": "Канадский доллар",
    "CDF": "Конголезский франк",
    "CHF": "Швейцарский франк",
    "CLF": "Условная денежная единица Чили",
    "CLP": "Чилийское песо",
    "CNY": "Китайский юань",
    "CNH": "Китайский юань (офшорный)",
    "COP": "Колумбийское песо",
    "CRC": "Коста-риканский колон",
    "CUC": "Кубинское конвертируемое песо",
    "CUP": "Кубинское песо",
    "CVE": "Кабо-Верде эскудо",
    "CZK": "Чешская крона",
    "DJF": "Франк Джибути",
    "DKK": "Датская крона",
    "DOP": "Доминиканское песо",
    "DZD": "Алжирский динар",
    "EGP": "Египетский фунт",
    "ERN": "Накфа Эритреи",
    "ETB": "Эфиопский быр",
    "EUR": "Евро",
    "FJD": "Фиджийский доллар",
    "FKP": "Фунт Фолклендских островов",
    "GBP": "Фунт стерлингов Соединенного королевства",
    "GEL": "Грузинский лари",
    "GGP": "Гернсийский фунт",
    "GHS": "Ганский седи",
    "GIP": "Гибралтарский фунт",
    "GMD": "Гамбийский даласи",
    "GNF": "Гвинейский франк",
    "GTQ": "Гватемальский кетсаль",
    "GYD": "Гайанский доллар",
    "HKD": "Гонконгский доллар",
    "HNL": "Гондурасская лемпира",
    "HRK": "Хорватская куна",
    "HTG": "Гаитянский гурд",
    "HUF": "Венгерский форинт",
    "IDR": "Индонезийская рупия",
    "ILS": "Израильский шекель",
    "IMP": "Фунт Острова Мэн",
    "INR": "Индийская рупия",
    "IQD": "Иракский динар",
    "IRR": "Иранский риал",
    "ISK": "Исландская крона",
    "JEP": "Джерсийский фунт",
    "JMD": "Ямайский доллар",
    "JOD": "Иорданский динар",
    "JPY": "Японская иена",
    "KES": "Кенийский шиллинг",
    "KGS": "Киргизский сом",
    "KHR": "Камбоджийский риель",
    "KMF": "Франк Коморских островов",
    "KPW": "Северокорейская вона",
    "KRW": "Южнокорейская вона",
    "KWD": "Кувейтский динар",
    "KYD": "Доллар Каймановых островов",
    "KZT": "Казахстанский тенге",
    "LAK": "Лаосский кип",
    "LBP": "Ливанский фунт",
    "LKR": "Шри-ланкийская рупия",
    "LRD": "Либерийский доллар",
    "LSL": "Лоти Лесото",
    "LTL": "Литовский лит",
    "LVL": "Латвийский лат",
    "LYD": "Ливийский динар",
    "MAD": "Марокканский дирхам",
    "MDL": "Молдавский лей",
    "MGA": "Малагасийский ариари",
    "MKD": "Македонский денар",
    "MMK": "Мьянманский кьят",
    "MNT": "Монгольский тугрик",
    "MOP": "Патака Макао",
    "MRU": "Мавританская угия",
    "MUR": "Маврикийская рупия",
    "MVR": "Мальдивская руфия",
    "MWK": "Малавийская квача",
    "MXN": "Мексиканское песо",
    "MYR": "Малайзийский ринггит",
    "MZN": "Мозамбикский метикал",
    "NAD": "Намибийский доллар",
    "NGN": "Нигерийская найра",
    "NIO": "Никарагуанская кордоба",
    "NOK": "Норвежская крона",
    "NPR": "Непальская рупия",
    "NZD": "Новозеландский доллар",
    "OMR": "Оманский риал",
    "PAB": "Панамский бальбоа",
    "PEN": "Перуанский соль",
    "PGK": "Кина Папуа - Новая Гвинея",
    "PHP": "Филиппинское песо",
    "PKR": "Пакистанская рупия",
    "PLN": "Польский злотый",
    "PYG": "Парагвайский гуарани",
    "QAR": "Катарский риал",
    "RON": "Румынский лей",
    "RSD": "Сербский динар",
    "RUB": "Российский рубль",
    "RWF": "Руандийский франк",
    "SAR": "Саудовский риал",
    "SBD": "Доллар Соломоновых островов",
    "SCR": "Сейшельская рупия",
    "SDG": "Суданский фунт",
    "SEK": "Шведская крона",
    "SGD": "Сингапурский доллар",
    "SHP": "Фунт Святой Елены",
    "SLE": "Леоне (Сьерра-Леоне)",
    "SLL": "Сьерра-леонский леоне",
    "SOS": "Сомалийский шиллинг",
    "SRD": "Суринамский доллар",
    "STD": "Добра Сан-Томе и Принсипи",
    "SVC": "Сальвадорский колон",
    "SYP": "Сирийский фунт",
    "SZL": "Лилангени Свазиленда",
    "THB": "Таиландский бат",
    "TJS": "Таджикский сомони",
    "TMT": "Туркменский манат",
    "TND": "Тунисский динар",
    "TOP": "Паанга Тонга",
    "TRY": "Турецкая лира",
    "TTD": "Тринидадский доллар",
    "TWD": "Тайваньский доллар",
    "TZS": "Танзанийский шиллинг",
    "UAH": "Украинская гривна",
    "UGX": "Угандийский шиллинг",
    "UYU": "Уругвайское песо",
    "UZS": "Узбекский сум",
    "VEF": "Венесуэльский боливар (старый)",
    "VES": "Венесуэльский боливар",
    "VND": "Вьетнамский донг",
    "VUV": "Вату Вануату",
    "WST": "Самоанская тала",
    "XAF": "Центральноафриканский франк",
    "XAG": "Серебро",
    "XAU": "Золото",
    "XCD": "Восточно-карибский доллар",
    "XDR": "Специальные права заимствования",
    "XOF": "Западноафриканский франк",
    "XPF": "Французский тихоокеанский франк",
    "YER": "Йеменский риал",
    "ZAR": "Южноафриканский рэнд",
    "ZMK": "Замбийская квача (старый)",
    "ZMW": "Замбийская квача",
    "ZWL": "Зимбабвийский доллар"
}

currency_names_en: Dict[str, str] = {
    "AED": "UAE Dirham",
    "AFN": "Afghan Afghani",
    "ALL": "Albanian Lek",
    "AMD": "Armenian Dram",
    "ANG": "Netherlands Antillean Guilder",
    "AOA": "Angolan Kwanza",
    "ARS": "Argentine Peso",
    "AUD": "Australian Dollar",
    "AWG": "Aruban Florin",
    "AZN": "Azerbaijani Manat",
    "BAM": "Bosnia-Herzegovina Convertible Mark",
    "BBD": "Barbadian Dollar",
    "BDT": "Bangladeshi Taka",
    "BGN": "Bulgarian Lev",
    "BHD": "Bahraini Dinar",
    "BIF": "Burundian Franc",
    "BMD": "Bermudian Dollar",
    "BND": "Brunei Dollar",
    "BOB": "Bolivian Boliviano",
    "BRL": "Brazilian Real",
    "BSD": "Bahamian Dollar",
    "BTC": "Bitcoin",
    "BTN": "Bhutanese Ngultrum",
    "BWP": "Botswana Pula",
    "BYN": "Belarusian Ruble",
    "BZD": "Belize Dollar",
    "CAD": "Canadian Dollar",
    "CDF": "Congolese Franc",
    "CHF": "Swiss Franc",
    "CLP": "Chilean Peso",
    "CNY": "Chinese Yuan",
    "COP": "Colombian Peso",
    "CRC": "Costa Rican Colón",
    "CUP": "Cuban Peso",
    "CZK": "Czech Koruna",
    "DKK": "Danish Krone",
    "DOP": "Dominican Peso",
    "DZD": "Algerian Dinar",
    "EGP": "Egyptian Pound",
    "ETB": "Ethiopian Birr",
    "EUR": "Euro",
    "FJD": "Fijian Dollar",
    "GBP": "British Pound",
    "GEL": "Georgian Lari",
    "GHS": "Ghanaian Cedi",
    "GIP": "Gibraltar Pound",
    "GMD": "Gambian Dalasi",
    "GNF": "Guinean Franc",
    "GTQ": "Guatemalan Quetzal",
    "GYD": "Guyanese Dollar",
    "HKD": "Hong Kong Dollar",
    "HNL": "Honduran Lempira",
    "HRK": "Croatian Kuna",
    "HTG": "Haitian Gourde",
    "HUF": "Hungarian Forint",
    "IDR": "Indonesian Rupiah",
    "ILS": "Israeli Shekel",
    "INR": "Indian Rupee",
    "IQD": "Iraqi Dinar",
    "IRR": "Iranian Rial",
    "ISK": "Icelandic Króna",
    "JMD": "Jamaican Dollar",
    "JOD": "Jordanian Dinar",
    "JPY": "Japanese Yen",
    "KES": "Kenyan Shilling",
    "KGS": "Kyrgystani Som",
    "KHR": "Cambodian Riel",
    "KMF": "Comorian Franc",
    "KRW": "South Korean Won",
    "KWD": "Kuwaiti Dinar",
    "KZT": "Kazakhstani Tenge",
    "LAK": "Lao Kip",
    "LBP": "Lebanese Pound",
    "LKR": "Sri Lankan Rupee",
    "LRD": "Liberian Dollar",
    "LSL": "Lesotho Loti",
    "LYD": "Libyan Dinar",
    "MAD": "Moroccan Dirham",
    "MDL": "Moldovan Leu",
    "MGA": "Malagasy Ariary",
    "MKD": "Macedonian Denar",
    "MMK": "Myanmar Kyat",
    "MNT": "Mongolian Tugrik",
    "MOP": "Macanese Pataca",
    "MRU": "Mauritanian Ouguiya",
    "MUR": "Mauritian Rupee",
    "MVR": "Maldivian Rufiyaa",
    "MWK": "Malawian Kwacha",
    "MXN": "Mexican Peso",
    "MYR": "Malaysian Ringgit",
    "MZN": "Mozambican Metical",
    "NAD": "Namibian Dollar",
    "NGN": "Nigerian Naira",
    "NIO": "Nicaraguan Córdoba",
    "NOK": "Norwegian Krone",
    "NPR": "Nepalese Rupee",
    "NZD": "New Zealand Dollar",
    "OMR": "Omani Rial",
    "PAB": "Panamanian Balboa",
    "PEN": "Peruvian Sol",
    "PGK": "Papua New Guinean Kina",
    "PHP": "Philippine Peso",
    "PKR": "Pakistani Rupee",
    "PLN": "Polish Zloty",
    "PYG": "Paraguayan Guarani",
    "QAR": "Qatari Riyal",
    "RON": "Romanian Leu",
    "RSD": "Serbian Dinar",
    "RUB": "Russian Ruble",
    "RWF": "Rwandan Franc",
    "SAR": "Saudi Riyal",
    "SBD": "Solomon Islands Dollar",
    "SCR": "Seychellois Rupee",
    "SDG": "Sudanese Pound",
    "SEK": "Swedish Krona",
    "SGD": "Singapore Dollar",
    "SHP": "Saint Helena Pound",
    "SLE": "Sierra Leonean Leone",
    "SOS": "Somali Shilling",
    "SRD": "Surinamese Dollar",
    "SYP": "Syrian Pound",
    "SZL": "Swazi Lilangeni",
    "THB": "Thai Baht",
    "TJS": "Tajikistani Somoni",
    "TMT": "Turkmenistani Manat",
    "TND": "Tunisian Dinar",
    "TOP": "Tongan Paʻanga",
    "TRY": "Turkish Lira",
    "TTD": "Trinidad and Tobago Dollar",
    "TWD": "New Taiwan Dollar",
    "TZS": "Tanzanian Shilling",
    "UAH": "Ukrainian Hryvnia",
    "UGX": "Ugandan Shilling",
    "USD": "United States Dollar",
    "UYU": "Uruguayan Peso",
    "UZS": "Uzbekistani Som",
    "VES": "Venezuelan Bolívar",
    "VND": "Vietnamese Dong",
    "VUV": "Vanuatu Vatu",
    "WST": "Samoan Tala",
    "XAF": "Central African CFA Franc",
    "XAG": "Silver",
    "XAU": "Gold",
    "XCD": "East Caribbean Dollar",
    "XDR": "Special Drawing Rights",
    "XOF": "West African CFA Franc",
    "XPF": "CFP Franc",
    "YER": "Yemeni Rial",
    "ZAR": "South African Rand",
    "ZMW": "Zambian Kwacha",
    "ZWL": "Zimbabwean Dollar"
}

currency_names_zh: Dict[str, str] = {
    "AED": "阿联酋迪拉姆",
    "AFN": "阿富汗尼",
    "ALL": "阿尔巴尼亚列克",
    "AMD": "亚美尼亚德拉姆",
    "ANG": "荷属安的列斯盾",
    "AOA": "安哥拉宽扎",
    "ARS": "阿根廷比索",
    "AUD": "澳大利亚元",
    "AWG": "阿鲁巴弗罗林",
    "AZN": "阿塞拜疆马纳特",
    "BAM": "波黑可兑换马克",
    "BBD": "巴巴多斯元",
    "BDT": "孟加拉塔卡",
    "BGN": "保加利亚列弗",
    "BHD": "巴林第纳尔",
    "BIF": "布隆迪法郎",
    "BMD": "百慕大元",
    "BND": "文莱元",
    "BOB": "玻利维亚诺",
    "BRL": "巴西雷亚尔",
    "BSD": "巴哈马元",
    "BTC": "比特币",
    "BTN": "不丹努尔特鲁姆",
    "BWP": "博茨瓦纳普拉",
    "BYN": "白俄罗斯卢布",
    "BZD": "伯利兹元",
    "CAD": "加拿大元",
    "CDF": "刚果法郎",
    "CHF": "瑞士法郎",
    "CLP": "智利比索",
    "CNY": "人民币",
    "COP": "哥伦比亚比索",
    "CRC": "哥斯达黎加科朗",
    "CUP": "古巴比索",
    "CZK": "捷克克朗",
    "DKK": "丹麦克朗",
    "DOP": "多米尼加比索",
    "DZD": "阿尔及利亚第纳尔",
    "EGP": "埃及镑",
    "ETB": "埃塞俄比亚比尔",
    "EUR": "欧元",
    "FJD": "斐济元",
    "GBP": "英镑",
    "GEL": "格鲁吉亚拉里",
    "GHS": "加纳塞地",
    "GIP": "直布罗陀镑",
    "GMD": "冈比亚达拉西",
    "GNF": "几内亚法郎",
    "GTQ": "危地马拉格查尔",
    "GYD": "圭亚那元",
    "HKD": "港元",
    "HNL": "洪都拉斯伦皮拉",
    "HRK": "克罗地亚库纳",
    "HTG": "海地古德",
    "HUF": "匈牙利福林",
    "IDR": "印度尼西亚卢比",
    "ILS": "以色列谢克尔",
    "INR": "印度卢比",
    "IQD": "伊拉克第纳尔",
    "IRR": "伊朗里亚尔",
    "ISK": "冰岛克朗",
    "JMD": "牙买加元",
    "JOD": "约旦第纳尔",
    "JPY": "日元",
    "KES": "肯尼亚先令",
    "KGS": "吉尔吉斯斯坦索姆",
    "KHR": "柬埔寨瑞尔",
    "KMF": "科摩罗法郎",
    "KRW": "韩元",
    "KWD": "科威特第纳尔",
    "KZT": "哈萨克斯坦坚戈",
    "LAK": "老挝基普",
    "LBP": "黎巴嫩镑",
    "LKR": "斯里兰卡卢比",
    "LRD": "利比里亚元",
    "LSL": "莱索托洛蒂",
    "LYD": "利比亚第纳尔",
    "MAD": "摩洛哥迪拉姆",
    "MDL": "摩尔多瓦列伊",
    "MGA": "马达加斯加阿里亚里",
    "MKD": "马其顿第纳尔",
    "MMK": "缅甸元",
    "MNT": "蒙古图格里克",
    "MOP": "澳门元",
    "MRU": "毛里塔尼亚乌吉亚",
    "MUR": "毛里求斯卢比",
    "MVR": "马尔代夫拉菲亚",
    "MWK": "马拉维克瓦查",
    "MXN": "墨西哥比索",
    "MYR": "马来西亚林吉特",
    "MZN": "莫桑比克梅蒂卡尔",
    "NAD": "纳米比亚元",
    "NGN": "尼日利亚奈拉",
    "NIO": "尼加拉瓜科多巴",
    "NOK": "挪威克朗",
    "NPR": "尼泊尔卢比",
    "NZD": "新西兰元",
    "OMR": "阿曼里亚尔",
    "PAB": "巴拿马巴波亚",
    "PEN": "秘鲁索尔",
    "PGK": "巴布亚新几内亚基那",
    "PHP": "菲律宾比索",
    "PKR": "巴基斯坦卢比",
    "PLN": "波兰兹罗提",
    "PYG": "巴拉圭瓜拉尼",
    "QAR": "卡塔尔里亚尔",
    "RON": "罗马尼亚列伊",
    "RSD": "塞尔维亚第纳尔",
    "RUB": "俄罗斯卢布",
    "RWF": "卢旺达法郎",
    "SAR": "沙特里亚尔",
    "SBD": "所罗门群岛元",
    "SCR": "塞舌尔卢比",
    "SDG": "苏丹镑",
    "SEK": "瑞典克朗",
    "SGD": "新加坡元",
    "SHP": "圣赫勒拿镑",
    "SLE": "塞拉利昂利昂",
    "SOS": "索马里先令",
    "SRD": "苏里南元",
    "SYP": "叙利亚镑",
    "SZL": "斯威士兰里兰吉尼",
    "THB": "泰铢",
    "TJS": "塔吉克斯坦索莫尼",
    "TMT": "土库曼斯坦马纳特",
    "TND": "突尼斯第纳尔",
    "TOP": "汤加潘加",
    "TRY": "土耳其里拉",
    "TTD": "特立尼达和多巴哥元",
    "TWD": "新台币",
    "TZS": "坦桑尼亚先令",
    "UAH": "乌克兰格里夫纳",
    "UGX": "乌干达先令",
    "USD": "美元",
    "UYU": "乌拉圭比索",
    "UZS": "乌兹别克斯坦索姆",
    "VES": "委内瑞拉玻利瓦尔",
    "VND": "越南盾",
    "VUV": "瓦努阿图瓦图",
    "WST": "萨摩亚塔拉",
    "XAF": "中非金融合作法郎",
    "XAG": "银",
    "XAU": "黄金",
    "XCD": "东加勒比元",
    "XDR": "特别提款权",
    "XOF": "西非法郎",
    "XPF": "太平洋法郎",
    "YER": "也门里亚尔",
    "ZAR": "南非兰特",
    "ZMW": "赞比亚克瓦查",
    "ZWL": "津巴布韦元"
}

@cached("currencylayer:quotes")
def fetch_usd_quotes() -> Dict[str, float]:
    logger.debug("Fetching currencylayer quotes")
    try:
        r = requests.get(
            BASE_URL,
            params={"access_key": CURRENCYLAYER_API_KEY},
            timeout=REQUEST_TIMEOUT,
        )
    except requests.RequestException as exc:
        logger.warning("currencylayer request failed: %s", exc)
        raise ExchangeRateError("Не удалось связаться с API currencylayer.") from exc

    try:
        r.raise_for_status()
    except requests.HTTPError as exc:
        logger.warning("currencylayer returned HTTP %s", r.status_code)
        raise ExchangeRateError(f"API currencylayer вернул ошибку {r.status_code}.") from exc

    try:
        d = r.json()
    except ValueError as exc:
        logger.warning("currencylayer returned invalid JSON")
        raise ExchangeRateError("API currencylayer вернул некорректный ответ.") from exc

    if not d.get("success"):
        info = d.get("error", {}).get("info") or "unknown API error"
        logger.warning("currencylayer API error: %s", info)
        raise ExchangeRateError(f"Ошибка currencylayer: {info}")

    logger.info("Loaded %s currencylayer quotes", len(d.get("quotes", {})))
    return d["quotes"]

def derive_cross_rates(base_code: str) -> Dict[str, float]:
    q = fetch_usd_quotes()
    usd_to_base = q.get(f"USD{base_code}")
    if not usd_to_base:
        raise RuntimeError(f"USD{base_code} not present")
    cross: Dict[str, float] = {}
    for pair, usd_to_target in q.items():
        if pair.startswith("USD"):
            target = pair[3:]
            cross[target] = usd_to_target / usd_to_base
    cross[base_code] = 1.0
    return cross

def label(code: str, lang: str = "ru") -> str:
    names = {
        "en": currency_names_en,
        "ru": currency_names_ru,
        "zh": currency_names_zh,
    }.get(lang, currency_names_en)
    return names.get(code, code)


def table_for_base(base_code: str, lang: str = "ru") -> List[Tuple[float, str, str]]:
    cross = derive_cross_rates(base_code)
    rows: List[Tuple[float, str, str]] = [(amt, code, label(code, lang)) for code, amt in cross.items()]
    rows.sort(key=lambda r: r[1])
    return rows